# Generated by Django 3.2.9 on 2021-12-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=200)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Diapositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('fecha_adquisicion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=200)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Valvula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('diapositivos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diapositivos')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='0', max_length=200)),
                ('tipo', models.CharField(choices=[('domestico', 'Domestico'), ('empresarial', 'Empresarial')], max_length=100)),
                ('usuario_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.CharField(max_length=100, unique=True)),
                ('costo', models.FloatField()),
                ('fecha_pago', models.DateTimeField(auto_now=True)),
                ('planes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planes')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_maximo', models.FloatField()),
                ('valor_minimo', models.FloatField()),
                ('humedad', models.IntegerField()),
                ('fecha_adquisicion', models.DateTimeField(auto_now=True)),
                ('diapositivos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diapositivos')),
            ],
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='diapositivos',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
    ]
