# Generated by Django 3.2.9 on 2021-12-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapositivos',
            name='fecha_adquisicion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='errores',
            name='fecha_envio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='fecha_adquisicion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
    ]
