# Generated by Django 3.2.9 on 2021-12-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tipo_errores_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapositivos',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
    ]
