# Generated by Django 3.2.9 on 2021-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_diapositivos_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapositivos',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diapositivos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='errores',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='humedad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='valor_maximo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='valor_minimo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')]),
        ),
    ]
