# Generated by Django 3.2.9 on 2021-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211205_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='diapositivos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='diapositivos'),
        ),
    ]
