# Generated by Django 3.2.9 on 2021-12-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_diapositivos_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planes',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
