# Generated by Django 3.2.9 on 2021-12-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_usuario_id_planes_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planes',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
