# Generated by Django 3.2.9 on 2021-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_usuario_planes_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='planes_id',
            new_name='planes',
        ),
    ]
