# Generated by Django 3.2.9 on 2021-12-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211205_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errores',
            name='fecha_envio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
