# Generated by Django 3.2.9 on 2021-12-07 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_alter_errores_fecha_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='usuarios',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
