# Generated by Django 3.2.9 on 2021-12-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_planes_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='usuarios',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
    ]
