# Generated by Django 3.2.9 on 2021-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211207_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='opciones',
            name='humedad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='valor_maximo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='valor_minimo',
            field=models.IntegerField(),
        ),
    ]
