# Generated by Django 3.2.9 on 2021-12-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='plan',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
