# Generated by Django 3.2.9 on 2021-12-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_planes_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='planes_id',
        ),
        migrations.AddField(
            model_name='planes',
            name='usuario_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.usuarios'),
        ),
    ]
