# Generated by Django 3.2.9 on 2021-12-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211204_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administradores',
        ),
        migrations.RemoveField(
            model_name='errores',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='diapositivos_id',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='planes_id',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='valvula',
            name='diapositivos_id',
        ),
        migrations.DeleteModel(
            name='Diapositivos',
        ),
        migrations.DeleteModel(
            name='Errores',
        ),
        migrations.DeleteModel(
            name='Opciones',
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.DeleteModel(
            name='Planes',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Valvula',
        ),
    ]
